export const ActionTypes = {
    FETCH_TODOS: 'FETCH_TODOS',
    SET_TODOS: 'SET_TODOS',
    DELETE_SINGLE_TODO: 'DELETE_SINGLE_TODO',
    DELETE_MULTIPLE_TODO: 'DELETE_MULTIPLE_TODO',
    ADD_NEW_TODO: 'ADD_NEW_TODO',
};